---
title: "code demo"
author: "Anna Flieder"
date: "12/4/2021"
output: html_document
---

```{r, warning=FALSE, message=FALSE}
library(tidyverse)
library(lubridate)
library(knitr)
library(reshape2)
library(car)
library(deSolve)
library(readxl)
```

```{r}
#u= fraction of like-gendered individuals in level above
#v= fraction of like-gendered individuals in current level
#lambda= strength of homophilic tendency
#b= bias (b>0.5 means women are favored)

#probability of someone seeking promotion to next level
P_func <- function(u, v, lambda){
  e <- exp(1)
  denom <- 1 + e^(-lambda*(u-v))
  return(1/denom)
}

#fraction of women in applicant pool
F0_func <- function(u, v, lambda){
  num <- v*P_func(u, v, lambda)
  denom <- num + ((1-v)*(P_func(1-u, 1-v, lambda)))
  return(num/denom)
}

#fraction of women promoted to next level
F_func <- function(u, v, lambda, b){
  num <- b*v*P_func(u, v, lambda)
  denom <- num + ((1-b)*(1-v)*P_func(1-u, 1-v, lambda))
  return(num/denom)
}
```

## MODEL PARAMETERS

```{r}
capital_r <- c(1/4, 1/5, 1/6, 1/7, 1/9, 1/15)

n <- c(13, 8, 5, 3, 2, 1)

times <- seq(from=0,to=150,by=1)

xstart <- c(0.4, 0.3, 0.2, 0.1, 0.05, 0.01)

lambda <- 2

b <- 0.5

params <- list(cap_r = capital_r, cap_n = n, lambda = lambda, bias = b)
```

```{r}
full_model <- function (t, x, parms) {
  x0 <- 0.5
  x1 <- x[1]
  x2 <- x[2]
  x3 <- x[3]
  x4 <- x[4]
  x5 <- x[5]
  x6 <- x[6]
  cap_r <- parms$cap_r
  L <- length(cap_r)
  cap_n <- parms$cap_n
  lambda <- parms$lambda
  b <- parms$bias
  low_r <- vector(mode="numeric", length=length(cap_r))
  for(j in seq_along(cap_r)){
    products <- vector(mode="numeric", length=length((j+1):L))
      for(k in seq_along(products)){
         products[k] <- cap_r[j+k]*cap_n[j+k]
      }
    num <- sum(products)
    denom <- cap_r[j] * cap_n[j]
    final <- num/denom
    low_r[j] <- final
  }
  0 -> low_r[is.na(low_r)]
  dx1dt <- (cap_r[1]*(1+low_r[1])*F_func(u = x1, v = x0, lambda = lambda, b = b)) - (cap_r[1]*x1) - 
    (cap_r[1]*low_r[1]*F_func(u = x2, v = x1, lambda = lambda, b = b))
  dx2dt <- (cap_r[2]*(1+low_r[2])*F_func(u = x2, v = x1, lambda = lambda, b = b)) - (cap_r[2]*x2) - 
    (cap_r[2]*low_r[2]*F_func(u = x3, v = x2, lambda = lambda, b = b))
  dx3dt <- (cap_r[3]*(1+low_r[3])*F_func(u = x3, v = x2, lambda = lambda, b = b)) - (cap_r[3]*x3) - 
    (cap_r[3]*low_r[3]*F_func(u = x4, v = x3, lambda = lambda, b = b))
  dx4dt <- (cap_r[4]*(1+low_r[4])*F_func(u = x4, v = x3, lambda = lambda, b = b)) - (cap_r[4]*x4) - 
    (cap_r[4]*low_r[4]*F_func(u = x5, v = x4, lambda = lambda, b = b))
  dx5dt <- (cap_r[5]*(1+low_r[5])*F_func(u = x5, v = x4, lambda = lambda, b = b)) - (cap_r[5]*x5) - 
    (cap_r[5]*low_r[5]*F_func(u = x6, v = x5, lambda = lambda, b = b))
  dx6dt <- (cap_r[6]*F_func(u = x6, v = x5, lambda = lambda, b = b)) - (cap_r[6]*x6)
  derivs <- c(dx1dt, dx2dt, dx3dt, dx4dt, dx5dt, dx6dt)
  list(derivs)
}

full_output <- ode(y = xstart, times = times, func = full_model, parms = params)

#check that the algorithm converged
diagnostics(full_output)

full_output <- as.data.frame(full_output)
head(full_output)
names(full_output) <- c("time", "undergrad", "grad", "postdoc", "tenure track", "tenured prof", "full prof")

full_data <- melt(full_output, id.vars = "time")
head(full_data)
full_data %>% ggplot(aes(x=time, y=value, color=variable)) +
  geom_line() +
  labs(x="Time", y="Fraction Women", color="Levels") +
  theme_bw() +
  scale_y_continuous(breaks=c(0, 0.25, 0.5, 0.75, 1)) +
  ylim(0,1)
```


## graph multiple parameter values
```{r}
bias_test <- c(0.2, 0.2, 0.7, 0.7)
homophily_test <- c(4, 1, 4, 1)

trials <- if(length(bias_test) == length(homophily_test)){
  length(bias_test)
  } else{
  0
}

varied_full_data <- vector(mode="list", length=trials)

for(i in seq_len(trials)){
  bias_name <- paste0("b=", bias_test[i])
  homo_name <- paste0("l=", homophily_test[i])
  names(varied_full_data)[i] <- paste(bias_name, homo_name, sep = ",")
}

for(i in seq_len(trials)){
  b <- bias_test[i]
  l <- homophily_test[i]
  params <- list(cap_r = capital_r, cap_n = n, lambda = l, bias = b)
  dat <- ode(y = xstart, times = times, func = full_model, parms = params)
  dat <- as.data.frame(dat)
  names(dat) <- c("time", "undergrad", "grad", "postdoc", "tenure track", "tenured prof", "full prof")
  dat_use <- melt(dat, id.vars = "time")
  dat_use <- dat_use %>% mutate(bias=b, homophily=l)
  varied_full_data[[i]] <- dat_use
}

entire_full_model <- do.call(rbind, varied_full_data)
head(entire_full_model)

entire_full_model %>% ggplot(aes(x=time, y=value, color=variable)) + 
  geom_line() +
  theme_bw() +
  facet_grid(bias ~ homophily, labeller = label_both) +
  labs(x="Time", y="Fraction Women", color="Levels", title = "Full Model")
```