---
title: "fit our data"
author: "Anna Flieder"
date: "12/1/2021"
output: html_document
---

```{r, warning=FALSE, message=FALSE}
library(tidyverse)
library(lubridate)
library(knitr)
library(reshape2)
library(car)
library(deSolve)
library(readxl)
library(minpack.lm) # library for least squares fit using levenberg-marquart algorithm
library(FME)
```

## MODEL FUNCTIONS
```{r}
e <- exp(1)

P_func <- function(u, v, lambda){
  e <- exp(1)
  denom <- 1 + e^(-lambda*(u-v))
  return(1/denom)
}

#fraction of women in applicant pool
F0_func <- function(u, v, lambda){
  num <- v*P_func(u, v, lambda)
  denom <- num + ((1-v)*(P_func(1-u, 1-v, lambda)))
  return(num/denom)
}

#fraction of women promoted to next level
#b= bias (b>0.5 means women are favored)
F_func <- function(u, v, lambda, b){
  num <- b*v*P_func(u, v, lambda)
  denom <- num + ((1-b)*(1-v)*P_func(1-u, 1-v, lambda))
  return(num/denom)
}

full_model <- function (t, x, parms) {
  x0 <- parms$x0
  x1 <- x[1]
  x2 <- x[2]
  x3 <- x[3]
  x4 <- x[4]
  x5 <- x[5]
  cap_r <- parms$cap_r
  L <- length(cap_r)
  n <- parms$cap_n
  lambda <- parms$lambda
  b <- parms$bias
  low_r <- vector(mode="numeric", length=length(cap_r))
  for(j in seq_along(cap_r)){
  products <- vector(mode="numeric", length=length((j+1):L))
  for(k in seq_along(products)){
    products[k] <- cap_r[j+k]*n[j+k]
    }
  num <- sum(products)
  denom <- cap_r[j] * n[j]
  final <- num/denom
  low_r[j] <- final
  }
  0 -> low_r[is.na(low_r)]
  dx1dt <- (cap_r[1]*(1+low_r[1])*F_func(u = x1, v = x0, lambda = lambda, b = b)) - (cap_r[1]*x1) - (cap_r[1]*low_r[1]*F_func(u = x2, v = x1, lambda = lambda, b = b))
  dx2dt <- (cap_r[2]*(1+low_r[2])*F_func(u = x2, v = x1, lambda = lambda, b = b)) - (cap_r[2]*x2) - (cap_r[2]*low_r[2]*F_func(u = x3, v = x2, lambda = lambda, b = b))
  dx3dt <- (cap_r[3]*(1+low_r[3])*F_func(u = x3, v = x2, lambda = lambda, b = b)) - (cap_r[3]*x3) - (cap_r[3]*low_r[3]*F_func(u = x4, v = x3, lambda = lambda, b = b))
  dx4dt <- (cap_r[4]*(1+low_r[4])*F_func(u = x4, v = x3, lambda = lambda, b = b)) - (cap_r[4]*x4) - (cap_r[4]*low_r[4]*F_func(u = x5, v = x4, lambda = lambda, b = b))
  dx5dt <- (cap_r[5]*F_func(u = x5, v = x4, lambda = lambda, b = b)) - (cap_r[5]*x5)
  derivs <- c(dx1dt, dx2dt, dx3dt, dx4dt, dx5dt)
  list(derivs)
}


barnard_model <- function (t, x, parms) {
  x0 <- parms$x0
  x1 <- x[1]
  x2 <- x[2]
  x3 <- x[3]
  x4 <- x[4]
  cap_r <- parms$cap_r
  L <- length(cap_r)
  n <- parms$cap_n
  lambda <- parms$lambda
  b <- parms$bias
  low_r <- vector(mode="numeric", length=length(cap_r))
  for(j in seq_along(cap_r)){
  products <- vector(mode="numeric", length=length((j+1):L))
  for(k in seq_along(products)){
    products[k] <- cap_r[j+k]*n[j+k]
    }
  num <- sum(products)
  denom <- cap_r[j] * n[j]
  final <- num/denom
  low_r[j] <- final
  }
  0 -> low_r[is.na(low_r)]
  dx1dt <- (cap_r[1]*(1+low_r[1])*F_func(u = x1, v = x0, lambda = lambda, b = b)) - (cap_r[1]*x1) - (cap_r[1]*low_r[1]*F_func(u = x2, v = x1, lambda = lambda, b = b))
  dx2dt <- (cap_r[2]*(1+low_r[2])*F_func(u = x2, v = x1, lambda = lambda, b = b)) - (cap_r[2]*x2) - (cap_r[2]*low_r[2]*F_func(u = x3, v = x2, lambda = lambda, b = b))
  dx3dt <- (cap_r[3]*(1+low_r[3])*F_func(u = x3, v = x2, lambda = lambda, b = b)) - (cap_r[3]*x3) - (cap_r[3]*low_r[3]*F_func(u = x4, v = x3, lambda = lambda, b = b))
  dx4dt <- (cap_r[4]*F_func(u = x4, v = x3, lambda = lambda, b = b)) - (cap_r[4]*x4)
  derivs <- c(dx1dt, dx2dt, dx3dt, dx4dt)
  list(derivs)
}
```


## ALL UNIVERSITY DATA
```{r}
university_wide <- read.csv("clean_wide_data.csv")
university_wide <- university_wide %>% select(-X) %>% as.data.frame()
university_wide

university_vert <- melt(university_wide, id.vars="time")
university_vert
```


## ALL UNIVERSITY PARAMETERS
```{r}
uni_starts <- university_wide[1, c("lecturer", "instructor", "assistant.professor", "associate.professor", "full.professor")]
uni_starts <- as.numeric(uni_starts)
uni_starts

uni_years <- unique(university_wide$time)
uni_years

#LSTUDY = 3 is grad students
grad_data <- read.csv("data/ef2020a.csv")
grad_data <- grad_data %>% select(UNITID, LSTUDY, EFTOTLT, EFTOTLW) %>% filter(LSTUDY == 3)
graduate_frac <- sum(grad_data$EFTOTLW)/sum(grad_data$EFTOTLT)
graduate_frac

#ASK KATHY ABOUT RETIREMENT/LEAVE RATES AT EACH LEVEL AND RELATIVE SIZE
uni_cap_r <- c(1/4, 1/5, 1/6, 1/7, 1/9)
uni_n <- c(13, 8, 5, 3, 2)

uni_lambda_est <- 0.5
uni_b_est <- 0.5

uni_params_est <- list(cap_r = uni_cap_r, cap_n = uni_n, lambda = uni_lambda_est, bias = uni_b_est, x0=graduate_frac)
uni_params_est
```



## ALL UNIVERSITY FITTING

https://cran.r-project.org/web/packages/FME/FME.pdf
```{r}
#run the cost function, necessary for modFit
uni_cost_func <- function(p) {
  uni_params_est$lambda <- p[1]
  uni_params_est$bias <- p[2]
  est <- ode(y = uni_starts, times = uni_years, func = full_model, parms = uni_params_est)
  est <- as.data.frame(est)
  names(est) <- c("time", "lecturer", "instructor", "assistant.professor", "associate.professor", "full.professor")
  #INSERT REAL DATA HERE NEXT TO EST
  return(modCost(est, university_wide))
}

#fits the model to your estimations
uni_fit <- modFit(p = c(lambda = uni_lambda_est, bias = uni_b_est), 
                  f = uni_cost_func, method="Nelder-Mead")

#estimates the parameters in your data
summary(uni_fit)

uni_parms <- as.data.frame(summary(uni_fit)$par)
uni_parms
```

## VISUALIZE ALL UNIVERSITY FITTING
```{r}
uni_fit_params <- list(cap_r = uni_cap_r, cap_n = uni_n, lambda = uni_parms["lambda", "Estimate"], 
                       bias = uni_parms["bias", "Estimate"], x0=graduate_frac)

uni_fit_ode <- ode(y = uni_starts, times = uni_years, func = full_model, parms = uni_fit_params)

uni_fit_ode <- as.data.frame(uni_fit_ode)
names(uni_fit_ode) <- c("year", "lecturer", "instructor", "assistant.professor", "associate.professor", "full.professor")

uni_fit_data <- melt(uni_fit_ode, id.vars = "year") %>% arrange(year)
head(uni_fit_data)

uni_fit_graph <- uni_fit_data %>% ggplot(aes(x=year, y=value, color=variable)) +
  geom_line() +
  labs(x="Year", y="Fraction Women", color="Levels", title = "Fitted Data") +
  theme_bw()
uni_actual_graph <- university_vert %>% ggplot(aes(x=time, y=value, color=variable)) +
  geom_line() + 
  labs(x="Year", y="Fraction Women", color="Levels", title = "Actual Data") +
  theme_bw()
grid.arrange(uni_fit_graph, uni_actual_graph)

predict_uni <- ode(y = uni_starts, times = 1993:2100, func = full_model, parms = uni_fit_params)
predict_uni <- as.data.frame(predict_uni)
names(predict_uni) <- c("time", "lecturer", "instructor", "assistant.professor", "associate.professor", "full.professor")
head(predict_uni)
predict_uni_dat <- melt(predict_uni, id.vars = "time") %>% arrange(time) %>% mutate(source="fit") %>% as.data.frame()
head(predict_uni_dat)
university_vert <- university_vert %>% mutate(source="original") %>% as.data.frame()
head(university_vert)
names(university_vert) == names(predict_uni_dat)
uni_comparison <- rbind(predict_uni_dat, university_vert)
head(uni_comparison)
ggplot(uni_comparison, aes(x=time, y=value, color=variable)) +
  geom_line(aes(linetype=source)) +
  labs(x="Year", y="Fraction Women", color="Levels", title = "All Universities, Fitted vs. Original") +
  theme_bw()
```



## COLUMBIA DATA FITTING

## COLUMBIA DATA
```{r}
columbia_wide <- read.csv("columbia_clean_wide_data.csv")
columbia_wide <- columbia_wide %>% select(-X) %>% as.data.frame()
columbia_wide

columbia_vert <- melt(columbia_wide, id.vars="time")
columbia_vert
```


## COLUMBIA PARAMETERS
```{r}
cu_starts <- columbia_wide[1, c("lecturer", "instructor", "assistant.professor", "associate.professor", "full.professor")]
cu_starts <- as.numeric(cu_starts)
cu_starts

cu_years <- unique(columbia_wide$time)
cu_years

#LSTUDY = 3 is grad students
grad_data <- read.csv("data/ef2020a.csv")
grad_data <- grad_data %>% select(UNITID, LSTUDY, EFTOTLT, EFTOTLW) %>% filter(LSTUDY == 3)
graduate_frac <- sum(grad_data$EFTOTLW)/sum(grad_data$EFTOTLT)
graduate_frac

#ASK KATHY ABOUT RETIREMENT/LEAVE RATES AT EACH LEVEL AND RELATIVE SIZE
cu_cap_r <- c(1/4, 1/5, 1/6, 1/7, 1/9)
cu_n <- c(13, 8, 5, 3, 2)

cu_lambda_est <- 0.5
cu_b_est <- 0.4

cu_params_est <- list(cap_r = cu_cap_r, cap_n = cu_n, lambda = cu_lambda_est, bias = cu_b_est, x0=graduate_frac)
cu_params_est
```



## COLUMBIA FITTING
https://cran.r-project.org/web/packages/FME/FME.pdf
```{r}
#run the cost function, necessary for modFit
cu_cost_func <- function(p) {
  cu_params_est$lambda <- p[1]
  cu_params_est$bias <- p[2]
  est <- ode(y = cu_starts, times = cu_years, func = full_model, parms = cu_params_est)
  est <- as.data.frame(est)
  names(est) <- c("time", "lecturer", "instructor", "assistant.professor", "associate.professor", "full.professor")
  #INSERT REAL DATA HERE NEXT TO EST
  return(modCost(est, columbia_wide))
}

#fits the model to your estimations
cu_fit <- modFit(p = c(lambda = cu_lambda_est, bias = cu_b_est), 
                  f = cu_cost_func, method="Nelder-Mead")

#estimates the parameters in your data
summary(cu_fit)

cu_parms <- as.data.frame(summary(cu_fit)$par)
cu_parms
```

## VISUALIZE COLUMBIA FITTING
```{r}
cu_fit_params <- list(cap_r = cu_cap_r, cap_n = cu_n, lambda = cu_parms["lambda", "Estimate"], 
                       bias = cu_parms["bias", "Estimate"], x0=graduate_frac)

cu_fit_ode <- ode(y = cu_starts, times = cu_years, func = full_model, parms = cu_fit_params)

cu_fit_ode <- as.data.frame(cu_fit_ode)
names(cu_fit_ode) <- c("year", "lecturer", "instructor", "assistant.professor", "associate.professor", "full.professor")

cu_fit_data <- melt(cu_fit_ode, id.vars = "year") %>% arrange(year)
head(cu_fit_data)

cu_fit_graph <- cu_fit_data %>% ggplot(aes(x=year, y=value, color=variable)) +
  geom_line() +
  labs(x="Year", y="Fraction Women", color="Levels", title = "Fitted Data") +
  theme_bw()
cu_actual_graph <- columbia_vert %>% ggplot(aes(x=time, y=value, color=variable)) +
  geom_line() + 
  labs(x="Year", y="Fraction Women", color="Levels", title = "Actual Data") +
  theme_bw()
grid.arrange(cu_fit_graph, cu_actual_graph)

predict_cu <- ode(y = cu_starts, times = 1993:2100, func = full_model, parms = cu_fit_params)
predict_cu <- as.data.frame(predict_cu)
names(predict_cu) <- c("time", "lecturer", "instructor", "assistant.professor", "associate.professor", "full.professor")
head(predict_cu)
predict_cu_dat <- melt(predict_cu, id.vars = "time") %>% arrange(time) %>% mutate(source="fit") %>% as.data.frame()
head(predict_cu_dat)
columbia_vert <- columbia_vert %>% mutate(source="original") %>% as.data.frame()
head(columbia_vert)
names(columbia_vert) == names(predict_cu_dat)
cu_comparison <- rbind(predict_cu_dat, columbia_vert)
head(cu_comparison)
ggplot(cu_comparison, aes(x=time, y=value, color=variable)) +
  geom_line(aes(linetype=source)) +
  labs(x="Year", y="Fraction Women", color="Levels", title = "Columbia, Fitted vs. Original") +
  theme_bw()
```



## BARNARD DATA FITTING

## BARNARD DATA
```{r}
barnard_wide <- read.csv("barnard_clean_wide_data.csv")
barnard_wide <- barnard_wide %>% select(-X) %>% as.data.frame()
barnard_wide

barnard_vert <- melt(barnard_wide, id.vars="time")
barnard_vert
```


## BARNARD PARAMETERS
```{r}
bc_starts <- barnard_wide[1, c("lecturer", "assistant.professor", "associate.professor", "full.professor")]
bc_starts <- as.numeric(bc_starts)
bc_starts

bc_years <- unique(barnard_wide$time)
bc_years

#LSTUDY = 3 is grad students
grad_data <- read.csv("data/ef2020a.csv")
grad_data <- grad_data %>% select(UNITID, LSTUDY, EFTOTLT, EFTOTLW) %>% filter(LSTUDY == 3)
graduate_frac <- sum(grad_data$EFTOTLW)/sum(grad_data$EFTOTLT)
graduate_frac

#ASK KATHY ABOUT RETIREMENT/LEAVE RATES AT EACH LEVEL AND RELATIVE SIZE
bc_cap_r <- c(1/4, 1/6, 1/7, 1/9)
bc_n <- c(13, 5, 3, 2)

bc_lambda_est <- 0.5
bc_b_est <- 0.6

bc_params_est <- list(cap_r = bc_cap_r, cap_n = bc_n, lambda = bc_lambda_est, bias = bc_b_est, x0=graduate_frac)
bc_params_est
```



## BARNARD FITTING
https://cran.r-project.org/web/packages/FME/FME.pdf
```{r}
#run the cost function, necessary for modFit
bc_cost_func <- function(p) {
  bc_params_est$lambda <- p[1]
  bc_params_est$bias <- p[2]
  est <- ode(y = bc_starts, times = bc_years, func = barnard_model, parms = bc_params_est)
  est <- as.data.frame(est)
  names(est) <- c("time", "lecturer", "assistant.professor", "associate.professor", "full.professor")
  #INSERT REAL DATA HERE NEXT TO EST
  return(modCost(est, barnard_wide))
}

#fits the model to your estimations
bc_fit <- modFit(p = c(lambda = bc_lambda_est, bias = bc_b_est), 
                  f = bc_cost_func, method="Nelder-Mead")

#estimates the parameters in your data
summary(bc_fit)

bc_parms <- as.data.frame(summary(bc_fit)$par)
bc_parms
```

## VISUALIZE BARNARD FITTING
```{r}
bc_fit_params <- list(cap_r = bc_cap_r, cap_n = bc_n, lambda = bc_parms["lambda", "Estimate"], 
                       bias = bc_parms["bias", "Estimate"], x0=graduate_frac)

bc_fit_ode <- ode(y = bc_starts, times = bc_years, func = barnard_model, parms = bc_fit_params)

bc_fit_ode <- as.data.frame(bc_fit_ode)
names(bc_fit_ode) <- c("year", "lecturer", "assistant.professor", "associate.professor", "full.professor")

bc_fit_data <- melt(bc_fit_ode, id.vars = "year") %>% arrange(year)
head(bc_fit_data)

bc_fit_graph <- bc_fit_data %>% ggplot(aes(x=year, y=value, color=variable)) +
  geom_line() +
  labs(x="Year", y="Fraction Women", color="Levels", title = "Fitted Data") +
  theme_bw()
bc_actual_graph <- barnard_vert %>% ggplot(aes(x=time, y=value, color=variable)) +
  geom_line() + 
  labs(x="Year", y="Fraction Women", color="Levels", title = "Actual Data") +
  theme_bw()
grid.arrange(bc_fit_graph, bc_actual_graph)

predict_bc <- ode(y = bc_starts, times = 1993:2100, func = barnard_model, parms = bc_fit_params)
predict_bc <- as.data.frame(predict_bc)
names(predict_bc) <- c("time", "lecturer", "assistant.professor", "associate.professor", "full.professor")
head(predict_bc)
predict_bc_dat <- melt(predict_bc, id.vars = "time") %>% arrange(time) %>% mutate(source="fit") %>% as.data.frame()
head(predict_bc_dat)
barnard_vert <- barnard_vert %>% mutate(source="original") %>% as.data.frame()
head(barnard_vert)
names(barnard_vert) == names(predict_bc_dat)
bc_comparison <- rbind(predict_bc_dat, barnard_vert)
head(bc_comparison)
ggplot(bc_comparison, aes(x=time, y=value, color=variable)) +
  geom_line(aes(linetype=source)) +
  labs(x="Year", y="Fraction Women", color="Levels", title = "Barnard, Fitted vs. Original") +
  theme_bw()
```

