---
title: "gender bias data"
author: "Anna Flieder"
date: "11/26/2021"
output: html_document
---

```{r, warning=FALSE, message=FALSE}
library(tidyverse)
library(lubridate)
library(knitr)
library(reshape2)
library(car)
library(deSolve)
library(readxl)
library(minpack.lm)
library(FME)
library(gridExtra)
```


2012-2020
```{r}
years1 <- 2012:2020
years1
data1 <- vector(mode="list", length=length(years1))
names(data1) <- years1

for(i in seq_along(data1)){
  name <- paste0("data/s", years1[i], "_is.csv")
  read_data <- read.csv(name)
  read_data <- read_data %>% mutate(year=years1[i])
  data1[[i]] <- as.data.frame(read_data)
}


clean_data1 <- function(x){
 portion <- x %>% select(year, UNITID, ARANK, HRTOTLT, HRTOTLM, HRTOTLW) %>% filter(ARANK %in% 1:5)
 summary <- portion %>% group_by(ARANK) %>% summarize(fraction=sum(HRTOTLW)/sum(HRTOTLT))
 fin <- as.data.frame(summary)
 fin <- fin %>% mutate(year = portion$year[1])
 return(as.data.frame(fin))
}

final_data1 <- lapply(data1, clean_data1)

final1 <- do.call(rbind, final_data1)

rankings <- c("full professor", "associate professor", "assistant professor", "instructor", "lecturer")
for(i in seq_along(unique(final1$ARANK))){
  condition <- final1$ARANK == i
  final1[condition, "ARANK"] <- rankings[i]
}

final1_wide <- dcast(final1, year ~ ARANK, value.var="fraction")
final1_wide

col_order <- c("year", "lecturer", "instructor", "assistant professor", "associate professor", "full professor")
final1_wide <- final1_wide[ , col_order]
names(final1_wide)[1] <- "time"
final1_wide

final1_vert <- final1_wide %>% melt(id.vars="time")
final1_vert
```

1999, 2001-2011
```{r}
years2 <- c(1999, 2001:2011)
data2 <- vector(mode="list", length=length(years2))
names(data2) <- years2

for(i in seq_along(data2)){
  name <- paste0("data/s", years2[i], "_f.csv")
  read_data <- read.csv(name)
  read_data <- read_data %>% mutate(year=years2[i])
  data2[[i]] <- as.data.frame(read_data)
}

data2.1 <- data2[9:12]
data2.2 <- data2[5:8]
data2.3 <- data2[1:4]

#same code for hierarchy levels
ranks_to_pull <- c(1:5, 8:12, 15:19)
full_prof <- c(1, 8, 15)
assoc_prof <- c(2, 9, 16)
assist_prof <- c(3, 10, 17)
inst <- c(4, 11, 18)
lect <- c(5, 12, 19)

clean_data2.1 <- function(x){
  names(x) <- toupper(names(x))
  dat <- x %>% select(YEAR, UNITID, ARANK, HRTOTLT, HRTOTLM, HRTOTLW) %>% filter(ARANK %in% ranks_to_pull)
  is_full_prof <- dat$ARANK %in% full_prof
  is_assoc_prof <- dat$ARANK %in% assoc_prof
  is_assist_prof <- dat$ARANK %in% assist_prof
  is_inst <- dat$ARANK %in% inst
  is_lect <- dat$ARANK %in% lect
  dat[is_full_prof, "ARANK"] <- "full professor"
  dat[is_assoc_prof, "ARANK"] <- "associate professor"
  dat[is_assist_prof, "ARANK"] <- "assistant professor"
  dat[is_inst, "ARANK"] <- "instructor"
  dat[is_lect, "ARANK"] <- "lecturer"
  sums <- dat %>% group_by(ARANK) %>% summarize(fraction=sum(HRTOTLW)/sum(HRTOTLT)) %>% mutate(year=dat$YEAR[1])
  sums <- as.data.frame(sums)
  return(sums)
}

#STAFF24=GRAND TOTAL
#STAFF15=TOTAL MEN
#STAFF16=TOTAL WOMEN
clean_data2.2 <- function(x){
  names(x) <- toupper(names(x))
  dat <- x %>% select(YEAR, UNITID, ARANK, STAFF24, STAFF15, STAFF16) %>% filter(ARANK %in% ranks_to_pull)
  is_full_prof <- dat$ARANK %in% full_prof
  is_assoc_prof <- dat$ARANK %in% assoc_prof
  is_assist_prof <- dat$ARANK %in% assist_prof
  is_inst <- dat$ARANK %in% inst
  is_lect <- dat$ARANK %in% lect
  dat[is_full_prof, "ARANK"] <- "full professor"
  dat[is_assoc_prof, "ARANK"] <- "associate professor"
  dat[is_assist_prof, "ARANK"] <- "assistant professor"
  dat[is_inst, "ARANK"] <- "instructor"
  dat[is_lect, "ARANK"] <- "lecturer"
  sums <- dat %>% group_by(ARANK) %>% summarize(fraction=sum(STAFF16)/sum(STAFF24)) %>% mutate(year=dat$YEAR[1])
  sums <- as.data.frame(sums)
  return(sums)
}

#STAFF16=TOTAL WOMEN
#STAFF15=TOTAL MEN
clean_data2.3 <- function(x){
  names(x) <- toupper(names(x))
  dat <- x %>% select(YEAR, UNITID, ARANK, STAFF15, STAFF16) %>% filter(ARANK %in% ranks_to_pull)
  is_full_prof <- dat$ARANK %in% full_prof
  is_assoc_prof <- dat$ARANK %in% assoc_prof
  is_assist_prof <- dat$ARANK %in% assist_prof
  is_inst <- dat$ARANK %in% inst
  is_lect <- dat$ARANK %in% lect
  dat[is_full_prof, "ARANK"] <- "full professor"
  dat[is_assoc_prof, "ARANK"] <- "associate professor"
  dat[is_assist_prof, "ARANK"] <- "assistant professor"
  dat[is_inst, "ARANK"] <- "instructor"
  dat[is_lect, "ARANK"] <- "lecturer"
  dat <- dat %>% mutate(TOTAL = STAFF15 + STAFF16)
  dat <- as.data.frame(dat)
  sums <- dat %>% group_by(ARANK) %>% summarize(fraction=sum(STAFF16)/sum(TOTAL)) %>% mutate(year=dat$YEAR[1])
  sums <- as.data.frame(sums)
  return(sums)
}


final_data2.1 <- lapply(data2.1, clean_data2.1)

final_data2.2 <- lapply(data2.2, clean_data2.2)

final_data2.3 <- lapply(data2.3, clean_data2.3)

final_data2 <- c(final_data2.1, final_data2.2, final_data2.3)
final2 <- do.call(rbind, final_data2)
final2_wide <- dcast(final2, year ~ ARANK, value.var="fraction")

final2_wide <- final2_wide[ ,col_order]
names(final2_wide)[1] <- "time"
final2_wide

final2_vert <- final2_wide %>% melt(id.vars="time")
final2_vert
```

1997, 1995
-STAFF15=total men
-STAFF16=total women
-need to manually compute total
-part F = full-time faculty by academic rank and tenure
1993
-staff15=total men
-staff16=total women
-need to manually compute total
```{r}
years3.1 <- c(1995, 1997)

data3.1 <- vector(mode="list", length=length(years3.1))
names(data3.1) <- years3.1
for(i in seq_along(data3.1)){
  name <- paste0("data/s", years3.1[i], "_s.csv")
  read_data <- read.csv(name)
  read_data <- read_data %>% mutate(year=years3.1[i])
  data3.1[[i]] <- as.data.frame(read_data)
}
head(data3.1[[1]])

full_profs3 <- c(86, 93, 100)
assoc_profs3 <- c(87, 94, 101)
assist_profs3 <- c(88, 95, 102)
inst3 <- c(89, 96, 103)
lect3 <- c(90, 97, 104)

ranks_to_pull3 <- c(full_profs3, assoc_profs3, assist_profs3, inst3, lect3)

clean_data3.1 <- function(x){
  names(x) <- toupper(names(x))
  dat <- x %>% select(YEAR, UNITID, PART, LINE, STAFF15, STAFF16) %>% filter(PART == "F", LINE %in% ranks_to_pull3)
  is_full_prof <- dat$LINE %in% full_profs3
  is_assoc_prof <- dat$LINE %in% assoc_profs3
  is_assist_prof <- dat$LINE %in% assist_profs3
  is_inst <- dat$LINE %in% inst3
  is_lect <- dat$LINE %in% lect3
  dat[is_full_prof, "LINE"] <- "full professor"
  dat[is_assoc_prof, "LINE"] <- "associate professor"
  dat[is_assist_prof, "LINE"] <- "assistant professor"
  dat[is_inst, "LINE"] <- "instructor"
  dat[is_lect, "LINE"] <- "lecturer"
  dat <- dat %>% mutate(TOTAL = STAFF15 + STAFF16)
  dat <- as.data.frame(dat)
  sums <- dat %>% group_by(LINE) %>% summarize(fraction=sum(STAFF16)/sum(TOTAL)) %>% mutate(year=dat$YEAR[1])
  sums <- as.data.frame(sums)
  return(sums)
}
clean_data3.1(data3.1[[1]])

final_data3.1 <- lapply(data3.1, clean_data3.1)

final3.1 <- do.call(rbind, final_data3.1)

final3.1
names(final3.1) <- c("ARANK", "fraction", "year")

years3.2 <- 1993

full_profs3.2 <- c(78, 85, 92)
assoc_profs3.2 <- c(79, 86, 93)
assist_profs3.2 <- c(80, 87, 94)
inst3.2 <- c(81, 88, 95)
lect3.2 <- c(82, 89, 96)
ranks_to_pull3.2 <- c(full_profs3.2, assoc_profs3.2, assist_profs3.2, inst3.2, lect3.2)

data3.2 <- read.csv("data/s1993_abcef.csv")
head(data3.2)
final_data3.2 <- data3.2 %>% select(unitid, line, staff15, staff16) %>% filter(line %in% ranks_to_pull3.2) %>%
  mutate(total= staff15+staff16)
is_full_prof <- final_data3.2$line %in% full_profs3.2
is_assoc_prof <- final_data3.2$line %in% assoc_profs3.2
is_assist_prof <- final_data3.2$line %in% assist_profs3.2
is_inst <- final_data3.2$line %in% inst3.2
is_lect <- final_data3.2$line %in% lect3.2
final_data3.2[is_full_prof, "line"] <- "full professor"
final_data3.2[is_assoc_prof, "line"] <- "associate professor"
final_data3.2[is_assist_prof, "line"] <- "assistant professor"
final_data3.2[is_inst, "line"] <- "instructor"
final_data3.2[is_lect, "line"] <- "lecturer"
final_data3.2

final3.2 <- final_data3.2 %>% group_by(line) %>% summarize(fraction= sum(staff16)/sum(total)) %>% mutate(year=years3.2)
final3.2 <- as.data.frame(final3.2)
final3.2
names(final3.2) <- c("ARANK", "fraction", "year")


final3 <- rbind(final3.1, final3.2)
final3

final3_wide <- dcast(final3, year ~ ARANK, value.var="fraction")
final3_wide <- final3_wide[ , col_order]
names(final3_wide)[1] <- "time"
final3_wide

final3_vert <- final3_wide %>% melt(id.vars="time")
final3_vert <- final3_vert %>% arrange(time)
final3_vert
```


ENTIRE DATA
```{r}
names(final2_wide)
wide_data <- rbind(final1_wide, final2_wide, final3_wide)
wide_data <- wide_data %>% arrange(time)
wide_data <- as.data.frame(wide_data)
wide_data

vert_data <- rbind(final1_vert, final2_vert, final3_vert)
vert_data <- vert_data %>% arrange(time)
vert_data

years <- unique(wide_data$time)

vert_data %>% ggplot(aes(x=time, y=value, color=variable)) +
  geom_line() +
  labs(x="Time", y="Fraction Women", color="Levels") +
  theme_bw()
```



## FITTING

Auxiliary functions
```{r}
#probability of someone seeking promotion to next level
#u= fraction of like-gendered individuals in level above
#v= fraction of like-gendered individuals in current level
#lambda= strength of homophilic tendency
e <- exp(1)

P_func <- function(u, v, lambda){
  e <- exp(1)
  denom <- 1 + e^(-lambda*(u-v))
  return(1/denom)
}

#fraction of women in applicant pool
F0_func <- function(u, v, lambda){
  num <- v*P_func(u, v, lambda)
  denom <- num + ((1-v)*(P_func(1-u, 1-v, lambda)))
  return(num/denom)
}

#fraction of women promoted to next level
#b= bias (b>0.5 means women are favored)
F_func <- function(u, v, lambda, b){
  num <- b*v*P_func(u, v, lambda)
  denom <- num + ((1-b)*(1-v)*P_func(1-u, 1-v, lambda))
  return(num/denom)
}
```


## MODEL VARIABLES

```{r}
capital_r <- c(1/4, 1/5, 1/6, 1/6, 1/12)
capital_r
L <- length(capital_r)

#the hierarchy sizes will be based on 2012-2020 sizes
sizes1 <- function(x){
  dat <- x %>% group_by(ARANK) %>% filter(ARANK %in% 1:5) %>% summarize(total=sum(HRTOTLT))
  dat <- as.data.frame(dat)
  is_full_prof <- dat$ARANK %in% full_prof
  is_assoc_prof <- dat$ARANK %in% assoc_prof
  is_assist_prof <- dat$ARANK %in% assist_prof
  is_inst <- dat$ARANK %in% inst
  is_lect <- dat$ARANK %in% lect
  dat[is_full_prof, "ARANK"] <- "full professor"
  dat[is_assoc_prof, "ARANK"] <- "associate professor"
  dat[is_assist_prof, "ARANK"] <- "assistant professor"
  dat[is_inst, "ARANK"] <- "instructor"
  dat[is_lect, "ARANK"] <- "lecturer"
  return(dat)
}
sizes_list1 <- lapply(data1, sizes1)
sizes_dat <- do.call(rbind, sizes_list1)
final_n <- sizes_dat %>% group_by(ARANK) %>% summarize(size=sum(total))
final_n <- as.data.frame(final_n)
final_n <- final_n[c(5,4,1,2,3), ]
final_n
ratios <- vector(mode="numeric", length=L)
for(i in seq_along(ratios)){
  ratios[i] <- final_n[i, 2]/final_n[1, 2]
}
ratios*3
#n is the rounded version of ratios, since we are talking about whole number of people, and the ratios are relatively close for ratios*3
n <- round(ratios*3)
n
```


# FULL MODEL

```{r}
#first I will see what percentage of grad students are female to find x0
grads <- read.csv("data/ef2020a.csv")
#LSTUDY=3 is graduate students
grads <- grads %>% select(UNITID, LSTUDY, EFTOTLT, EFTOTLW) %>% filter(LSTUDY == 3)
head(grads)
grad_fract <- sum(grads$EFTOTLW)/sum(grads$EFTOTLT)
grad_fract

full_model <- function (t, x, parms) {
  x0 <- grad_fract
  x1 <- x[1]
  x2 <- x[2]
  x3 <- x[3]
  x4 <- x[4]
  x5 <- x[5]
  cap_r <- parms$cap_r
  L <- length(cap_r)
  lambda <- parms$lambda
  b <- parms$bias
  low_r <- vector(mode="numeric", length=length(capital_r))
  for(j in seq_along(capital_r)){
  products <- vector(mode="numeric", length=length((j+1):L))
  for(k in seq_along(products)){
    products[k] <- capital_r[j+k]*n[j+k]
    }
  num <- sum(products)
  denom <- capital_r[j] * n[j]
  final <- num/denom
  low_r[j] <- final
  }
  0 -> low_r[is.na(low_r)]
  dx1dt <- (cap_r[1]*(1+low_r[1])*F_func(u = x1, v = x0, lambda = lambda, b = b)) - (cap_r[1]*x1) - (cap_r[1]*low_r[1]*F_func(u = x2, v = x1, lambda = lambda, b = b))
  dx2dt <- (cap_r[2]*(1+low_r[2])*F_func(u = x2, v = x1, lambda = lambda, b = b)) - (cap_r[2]*x2) - (cap_r[2]*low_r[2]*F_func(u = x3, v = x2, lambda = lambda, b = b))
  dx3dt <- (cap_r[3]*(1+low_r[3])*F_func(u = x3, v = x2, lambda = lambda, b = b)) - (cap_r[3]*x3) - (cap_r[3]*low_r[3]*F_func(u = x4, v = x3, lambda = lambda, b = b))
  dx4dt <- (cap_r[4]*(1+low_r[4])*F_func(u = x4, v = x3, lambda = lambda, b = b)) - (cap_r[4]*x4) - (cap_r[4]*low_r[4]*F_func(u = x5, v = x4, lambda = lambda, b = b))
  dx5dt <- (cap_r[5]*F_func(u = x5, v = x4, lambda = lambda, b = b)) - (cap_r[5]*x5)
  derivs <- c(dx1dt, dx2dt, dx3dt, dx4dt, dx5dt)
  list(derivs)
}
```

## FITTING

https://cran.r-project.org/web/packages/FME/FME.pdf
```{r}
#estimate your parameters
capital_r_est <- c(1/4, 1/5, 1/6, 1/6, 1/12)
L <- length(capital_r_est)
xstart <- as.numeric(wide_data[1, 2:6])
n_est <- n
lambda_est <- 2
b_est <- 0.5
params_est <- list(cap_r = capital_r_est, cap_n = n_est, lambda = lambda_est, bias = b_est)
params_est
times <- unique(wide_data$time)
times

#ensure that your real data has the same #columns, column names, class as full_output

test <- ode(y = xstart, times = times, func = full_model, parms = params_est)
test <- as.data.frame(test)
test

#run the cost function, necessary for modFit
cost_func <- function(p) {
  params_est$lambda <- p[1]
  params_est$bias <- p[2]
  est <- ode(y = xstart, times = times, func = full_model, parms = params_est)
  est <- as.data.frame(est)
  names(est) <- c("time", "lecturer", "instructor", "assistant professor", "associate professor", "full professor")
  #INSERT REAL DATA HERE INSTEAD OF FULL_OUTPUT
  return(modCost(est, wide_data))
}

#fits the model to your estimations
fit <- modFit(p = c(lambda = lambda_est, bias = b_est), f = cost_func, lower=0)

#estimates the parameters in your data
summary(fit)

fit_parm_est <- as.data.frame(summary(fit)$par)
fit_parm_est
```

```{r}
fit_params <- list(cap_r = capital_r, cap_n = n, lambda = fit_parm_est["lambda", "Estimate"], bias = fit_parm_est["bias", "Estimate"])

fit_ode <- ode(y = xstart, times = times, func = full_model, parms = fit_params)

fit_ode <- as.data.frame(fit_ode)
names(fit_ode) <- c("year", "lecturer", "instructor", "assistant professor", "associate professor", "full professor")

fit_data <- melt(fit_ode, id.vars = "year")
head(fit_data)
fit_graph <- fit_data %>% ggplot(aes(x=year, y=value, color=variable)) +
  geom_line() +
  labs(x="Year", y="Fraction Women", color="Levels", title = "Fitted Data") +
  theme_bw()
actual_graph <- vert_data %>% ggplot(aes(x=time, y=value, color=variable)) +
  geom_line() + 
  labs(x="Year", y="Fraction Women", color="Levels", title = "Actual Data") +
  theme_bw()
grid.arrange(fit_graph, actual_graph)
```


## COLUMBIA DATA
columbia UNITID = 190150

2012-2020
```{r}
clean_data1_col <- function(x){
 portion <- x %>% select(year, UNITID, ARANK, HRTOTLT, HRTOTLM, HRTOTLW) %>% filter(ARANK %in% 1:5, UNITID == 190150)
 summary <- portion %>% group_by(ARANK) %>% summarize(fraction=sum(HRTOTLW)/sum(HRTOTLT))
 fin <- as.data.frame(summary)
 fin <- fin %>% mutate(year = portion$year[1])
 return(as.data.frame(fin))
}

final_data1_col <- lapply(data1, clean_data1_col)

final1_col <- do.call(rbind, final_data1_col)
final1_col

rankings <- c("full professor", "associate professor", "assistant professor", "instructor", "lecturer")
for(i in seq_along(unique(final1_col$ARANK))){
  condition <- final1_col$ARANK == i
  final1_col[condition, "ARANK"] <- rankings[i]
}
final1_col

final1_col_wide <- dcast(final1_col, year ~ ARANK, value.var="fraction")
final1_col_wide

final1_col_wide <- final1_col_wide[ , col_order]
names(final1_col_wide)[1] <- "time"
final1_col_wide

final1_col_vert <- final1_col_wide %>% melt(id.vars="time")
```

2001-2011
```{r}
clean_data2.1_col <- function(x){
  names(x) <- toupper(names(x))
  dat <- x %>% select(YEAR, UNITID, ARANK, HRTOTLT, HRTOTLM, HRTOTLW) %>% filter(ARANK %in% ranks_to_pull, UNITID == 190150)
  is_full_prof <- dat$ARANK %in% full_prof
  is_assoc_prof <- dat$ARANK %in% assoc_prof
  is_assist_prof <- dat$ARANK %in% assist_prof
  is_inst <- dat$ARANK %in% inst
  is_lect <- dat$ARANK %in% lect
  dat[is_full_prof, "ARANK"] <- "full professor"
  dat[is_assoc_prof, "ARANK"] <- "associate professor"
  dat[is_assist_prof, "ARANK"] <- "assistant professor"
  dat[is_inst, "ARANK"] <- "instructor"
  dat[is_lect, "ARANK"] <- "lecturer"
  sums <- dat %>% group_by(ARANK) %>% summarize(fraction=sum(HRTOTLW)/sum(HRTOTLT)) %>% mutate(year=dat$YEAR[1])
  sums <- as.data.frame(sums)
  return(sums)
}

clean_data2.2_col<- function(x){
  names(x) <- toupper(names(x))
  dat <- x %>% select(YEAR, UNITID, ARANK, STAFF24, STAFF15, STAFF16) %>% filter(ARANK %in% ranks_to_pull, UNITID == 190150)
  is_full_prof <- dat$ARANK %in% full_prof
  is_assoc_prof <- dat$ARANK %in% assoc_prof
  is_assist_prof <- dat$ARANK %in% assist_prof
  is_inst <- dat$ARANK %in% inst
  is_lect <- dat$ARANK %in% lect
  dat[is_full_prof, "ARANK"] <- "full professor"
  dat[is_assoc_prof, "ARANK"] <- "associate professor"
  dat[is_assist_prof, "ARANK"] <- "assistant professor"
  dat[is_inst, "ARANK"] <- "instructor"
  dat[is_lect, "ARANK"] <- "lecturer"
  sums <- dat %>% group_by(ARANK) %>% summarize(fraction=sum(STAFF16)/sum(STAFF24)) %>% mutate(year=dat$YEAR[1])
  sums <- as.data.frame(sums)
  return(sums)
}

clean_data2.3_col <- function(x){
  names(x) <- toupper(names(x))
  dat <- x %>% select(YEAR, UNITID, ARANK, STAFF15, STAFF16) %>% filter(ARANK %in% ranks_to_pull, UNITID == 190150)
  is_full_prof <- dat$ARANK %in% full_prof
  is_assoc_prof <- dat$ARANK %in% assoc_prof
  is_assist_prof <- dat$ARANK %in% assist_prof
  is_inst <- dat$ARANK %in% inst
  is_lect <- dat$ARANK %in% lect
  dat[is_full_prof, "ARANK"] <- "full professor"
  dat[is_assoc_prof, "ARANK"] <- "associate professor"
  dat[is_assist_prof, "ARANK"] <- "assistant professor"
  dat[is_inst, "ARANK"] <- "instructor"
  dat[is_lect, "ARANK"] <- "lecturer"
  dat <- dat %>% mutate(TOTAL = STAFF15 + STAFF16)
  dat <- as.data.frame(dat)
  sums <- dat %>% group_by(ARANK) %>% summarize(fraction=sum(STAFF16)/sum(TOTAL)) %>% mutate(year=dat$YEAR[1])
  sums <- as.data.frame(sums)
  return(sums)
}


final_data2.1_col <- lapply(data2.1, clean_data2.1_col)

final_data2.2_col <- lapply(data2.2, clean_data2.2_col)

final_data2.3_col <- lapply(data2.3, clean_data2.3_col)

final_data2_col <- c(final_data2.1_col, final_data2.2_col, final_data2.3_col)
final2_col <- do.call(rbind, final_data2_col)
final2_col_wide <- dcast(final2_col, year ~ ARANK, value.var="fraction")
final2_col_wide <- final2_col_wide[ ,col_order]
names(final2_col_wide)[1] <- "time"
final2_col_wide

final2_col_vert <- final2_col_wide %>% melt(id.vars="time")
final2_col_vert
```

ENTIRE DATA
```{r}
wide_data_col <- rbind(final1_col_wide, final2_col_wide)
wide_data_col <- wide_data_col %>% arrange(time)
wide_data_col <- as.data.frame(wide_data_col)
wide_data_col

vert_data_col <- rbind(final1_col_vert, final2_col_vert)
vert_data_col <- vert_data_col %>% arrange(time)
vert_data_col <- as.data.frame(vert_data_col)
vert_data_col
```


## FITTING

https://cran.r-project.org/web/packages/FME/FME.pdf
```{r}
xstart <- as.numeric(wide_data_col[1, 2:6])
xstart
#estimate your parameters
lambda_est <- 2
b_est <- 0.4
params_est <- list(cap_r = capital_r, low_r = lowercase_r, lambda = lambda_est, bias = b_est)
params_est

#ensure that your real data has the same #columns, column names, class as full_output

#run the cost function, necessary for modFit
cost_func <- function(p) {
  params_est$lambda <- p[1]
  params_est$bias <- p[2]
  est <- ode(y = xstart, times = times, func = full_model, parms = params_est)
  est <- as.data.frame(est)
  names(est) <- c("time", "lecturer", "instructor", "assistant professor", "associate professor", "full professor")
  #INSERT REAL DATA HERE INSTEAD OF FULL_OUTPUT
  return(modCost(est, wide_data_col))
}

#fits the model to your estimations
fit <- modFit(p = c(lambda = lambda_est, bias = b_est), f = cost_func)

#estimates the parameters in your data
summary(fit)
fit_parm_est <- as.data.frame(summary(fit)$par)
fit_parm_est
```

```{r}
fit_params <- list(cap_r = capital_r, low_r = lowercase_r, lambda = fit_parm_est["lambda", "Estimate"], bias = fit_parm_est["bias", "Estimate"])

fit_ode <- ode(y = xstart, times = times, func = full_model, parms = fit_params)

fit_ode <- as.data.frame(fit_ode)
names(fit_ode) <- c("year", "lecturer", "instructor", "assistant professor", "associate professor", "full professor")

fit_data <- melt(fit_ode, id.vars = "year")
fit_graph <- fit_data %>% ggplot(aes(x=year, y=value, color=variable)) +
  geom_line() +
  labs(x="Year", y="Fraction Women", color="Levels", title = "Fitted Data") +
  theme_bw()
actual_graph <- vert_data_col %>% ggplot(aes(x=time, y=value, color=variable)) +
  geom_line() + 
  labs(x="Year", y="Fraction Women", color="Levels", title = "Actual Data") +
  theme_bw()
grid.arrange(fit_graph, actual_graph)
```

## BARNARD
189097

2012-2020
```{r}
clean_data1_bar <- function(x){
 portion <- x %>% select(year, UNITID, ARANK, HRTOTLT, HRTOTLM, HRTOTLW) %>% filter(ARANK %in% 1:5, UNITID == 189097)
 summary <- portion %>% group_by(ARANK) %>% summarize(fraction=sum(HRTOTLW)/sum(HRTOTLT))
 fin <- as.data.frame(summary)
 fin <- fin %>% mutate(year = portion$year[1])
 return(as.data.frame(fin))
}

final_data1_bar <- lapply(data1, clean_data1_bar)

final1_bar <- do.call(rbind, final_data1_bar)
final1_bar

rankings <- c("full professor", "associate professor", "assistant professor", "instructor", "lecturer")
for(i in seq_along(unique(final1_bar$ARANK))){
  condition <- final1_bar$ARANK == i
  final1_bar[condition, "ARANK"] <- rankings[i]
}
final1_bar

final1_bar_wide <- dcast(final1_bar, year ~ ARANK, value.var="fraction")
final1_bar_wide

bar_order <- c("year", "lecturer", "instructor", "assistant professor", "associate professor", "full professor")
final1_bar_wide <- final1_bar_wide[ , bar_order]
names(final1_bar_wide)[1] <- "time"
final1_bar_wide

final1_bar_vert <- final1_bar_wide %>% melt(id.vars="time")
```

2001-2011
```{r}
clean_data2.1_bar <- function(x){
  names(x) <- toupper(names(x))
  dat <- x %>% select(YEAR, UNITID, ARANK, HRTOTLT, HRTOTLM, HRTOTLW) %>% filter(ARANK %in% ranks_to_pull, UNITID == 189097)
  is_full_prof <- dat$ARANK %in% full_prof
  is_assoc_prof <- dat$ARANK %in% assoc_prof
  is_assist_prof <- dat$ARANK %in% assist_prof
  is_inst <- dat$ARANK %in% inst
  is_lect <- dat$ARANK %in% lect
  dat[is_full_prof, "ARANK"] <- "full professor"
  dat[is_assoc_prof, "ARANK"] <- "associate professor"
  dat[is_assist_prof, "ARANK"] <- "assistant professor"
  dat[is_inst, "ARANK"] <- "instructor"
  dat[is_lect, "ARANK"] <- "lecturer"
  sums <- dat %>% group_by(ARANK) %>% summarize(fraction=sum(HRTOTLW)/sum(HRTOTLT)) %>% mutate(year=dat$YEAR[1])
  sums <- as.data.frame(sums)
  return(sums)
}

clean_data2.2_bar<- function(x){
  names(x) <- toupper(names(x))
  dat <- x %>% select(YEAR, UNITID, ARANK, STAFF24, STAFF15, STAFF16) %>% filter(ARANK %in% ranks_to_pull, UNITID == 189097)
  is_full_prof <- dat$ARANK %in% full_prof
  is_assoc_prof <- dat$ARANK %in% assoc_prof
  is_assist_prof <- dat$ARANK %in% assist_prof
  is_inst <- dat$ARANK %in% inst
  is_lect <- dat$ARANK %in% lect
  dat[is_full_prof, "ARANK"] <- "full professor"
  dat[is_assoc_prof, "ARANK"] <- "associate professor"
  dat[is_assist_prof, "ARANK"] <- "assistant professor"
  dat[is_inst, "ARANK"] <- "instructor"
  dat[is_lect, "ARANK"] <- "lecturer"
  sums <- dat %>% group_by(ARANK) %>% summarize(fraction=sum(STAFF16)/sum(STAFF24)) %>% mutate(year=dat$YEAR[1])
  sums <- as.data.frame(sums)
  return(sums)
}

clean_data2.3_bar <- function(x){
  names(x) <- toupper(names(x))
  dat <- x %>% select(YEAR, UNITID, ARANK, STAFF15, STAFF16) %>% filter(ARANK %in% ranks_to_pull, UNITID == 189097)
  is_full_prof <- dat$ARANK %in% full_prof
  is_assoc_prof <- dat$ARANK %in% assoc_prof
  is_assist_prof <- dat$ARANK %in% assist_prof
  is_inst <- dat$ARANK %in% inst
  is_lect <- dat$ARANK %in% lect
  dat[is_full_prof, "ARANK"] <- "full professor"
  dat[is_assoc_prof, "ARANK"] <- "associate professor"
  dat[is_assist_prof, "ARANK"] <- "assistant professor"
  dat[is_inst, "ARANK"] <- "instructor"
  dat[is_lect, "ARANK"] <- "lecturer"
  dat <- dat %>% mutate(TOTAL = STAFF15 + STAFF16)
  dat <- as.data.frame(dat)
  sums <- dat %>% group_by(ARANK) %>% summarize(fraction=sum(STAFF16)/sum(TOTAL)) %>% mutate(year=dat$YEAR[1])
  sums <- as.data.frame(sums)
  return(sums)
}

final_data2.1_bar <- lapply(data2.1, clean_data2.1_bar)

final_data2.2_bar <- lapply(data2.2, clean_data2.2_bar)

final_data2.3_bar <- lapply(data2.3, clean_data2.3_bar)

final_data2_bar <- c(final_data2.1_bar, final_data2.2_bar, final_data2.3_bar)
final2_bar <- do.call(rbind, final_data2_bar)
final2_bar_wide <- dcast(final2_bar, year ~ ARANK, value.var="fraction")
final2_bar_wide <- final2_bar_wide[ ,bar_order]
names(final2_bar_wide)[1] <- "time"
final2_bar_wide

final2_bar_vert <- final2_bar_wide %>% melt(id.vars="time")
final2_bar_vert
```

```{r}

```


ENTIRE DATA
```{r}
wide_data_bar <- rbind(final1_bar_wide, final2_bar_wide)
wide_data_bar <- wide_data_bar %>% arrange(time)
wide_data_bar <- as.data.frame(wide_data_bar)
wide_data_bar

vert_data_bar <- rbind(final1_bar_vert, final2_bar_vert)
vert_data_bar <- vert_data_bar %>% arrange(time)
vert_data_bar <- as.data.frame(vert_data_bar)
vert_data_bar
```


## FITTING

https://cran.r-project.org/web/packages/FME/FME.pdf
```{r}
xstart <- as.numeric(wide_data_bar[1, 2:6])
xstart
#estimate your parameters
lambda_est <- 2
b_est <- 0.6
params_est <- list(cap_r = capital_r, low_r = lowercase_r, lambda = lambda_est, bias = b_est)
params_est

#ensure that your real data has the same #barumns, barumn names, class as full_output

#run the cost function, necessary for modFit
cost_func <- function(p) {
  params_est$lambda <- p[1]
  params_est$bias <- p[2]
  est <- ode(y = xstart, times = times, func = full_model, parms = params_est)
  est <- as.data.frame(est)
  names(est) <- c("time", "lecturer", "instructor", "assistant professor", "associate professor", "full professor")
  #INSERT REAL DATA HERE INSTEAD OF FULL_OUTPUT
  return(modCost(est, wide_data_bar))
}

#fits the model to your estimations
fit <- modFit(p = c(lambda = lambda_est, bias = b_est), f = cost_func)

#estimates the parameters in your data
summary(fit)
fit_parm_est <- as.data.frame(summary(fit)$par)
fit_parm_est
```

```{r}
fit_params <- list(cap_r = capital_r, low_r = lowercase_r, lambda = fit_parm_est["lambda", "Estimate"], bias = fit_parm_est["bias", "Estimate"])

fit_ode <- ode(y = xstart, times = times, func = full_model, parms = fit_params)

fit_ode <- as.data.frame(fit_ode)
names(fit_ode) <- c("year", "lecturer", "instructor", "assistant professor", "associate professor", "full professor")

fit_data <- melt(fit_ode, id.vars = "year")
fit_graph <- fit_data %>% ggplot(aes(x=year, y=value, color=variable)) +
  geom_line() +
  labs(x="Year", y="Fraction Women", color="Levels", title = "Fitted Data") +
  theme_bw()
actual_graph <- vert_data_bar %>% ggplot(aes(x=time, y=value, color=variable)) +
  geom_line() + 
  labs(x="Year", y="Fraction Women", color="Levels", title = "Actual Data") +
  theme_bw()
grid.arrange(fit_graph, actual_graph)
```
